### ISSUE TITLE
Can't use storescp on Ubuntu 20.04

### ISSUE THREAD

**Issue by Moonzenith** [knopkem/dicom-dimse-native#8]
HI, I'm runing a simple storescp, almost like the one in the example
''
```
const dimse = require('dicom-dimse-native')

dimse.startScp(JSON.stringify(
  {
      "source": {
          "aet": "LOCALAET",
          "ip" : "192.168.1.X",
          "port": "8080"
      },
"storagePath": "./data"
  }   
  ), (result) => {
      if (result && result.length > 0) {
          try
          {
              console.log(JSON.parse(result));
          }
          catch (e) {
              console.log(e, result);
          }
      }
});

```

But any operation made to this prints in the console:

```
DIMSE failure (aborting association): Data dictionary missing
```

I even have dcmtk globally installed with the `$DCM_DICT_DEFAULT_PATH` set to the global .dic file

What am I missing?

**Comment by knopkem** [comment]
Hi,
thanks for reporting this, I'll have a look at the linux version asap and come back to you. cheers

**Comment by knopkem** [comment]
This should be fixed now. Can you try with the latest version again? Thanks.

**Comment by Moonzenith** [comment]
Sorry to answer this late, I kinda solved it using `$DCMDICTPATH` as the env path to my global dictionary and it worked on loading the dictionary but using gingko now I'm getting

```
DIMSE failure (aborting association): DIMSE Failed to receive message
0006:0212 DIMSE Unsupported transfer syntax: 1.2.840.10008.1.2.1.99
```

Tested with the new version and removing the envs and still getting the same "new" error

Currently using dcm4che for my production app but still interested in making this work

**Comment by knopkem** [comment]
hi, sorry forgot about this. the issue is that your pacs is trying to use a transfer syntax (deflated explicit vr) which the proxy does not understand. Normally they should fall back to the default transfer syntax (implicit vr little endian) but somehow this is not the case. You should check the configuration of your pacs if you can change this. do you use C-GET or C-MOVE?

**Comment by Moonzenith** [comment]
GINKGO seems to not have that configuration, maybe I'm wrong with that and production PACS is third party and a total blackbox to me, I can make a request for that to my client, and I'm using C-MOVE (with your moveScu utility)

**Comment by knopkem** [comment]
I had a look at Gingko cadx and as it seems it is only a client (scu). Could you explain what your setup is and what you want to achieve?
